1. 每种行为发生的次数


In [3]:
import utils
import numpy as np
import pandas as pd
from collections import defaultdict
from matplotlib import pylab 

filename = './data/ann.txt'
acts = utils.ExtractActivities(filename)

activities,binary_sensors,continue_sensors = utils.LoadMeta(utils.metalabel)
activities_counts = defaultdict(int)
activities_labels = []
for act in acts:
    activities_counts[act[0]] += 1
    activities_labels.append(act[0])
activities_num = []

# 训练数据集 2655 * N：N为特征个数
training_data = np.array([[] for x in range(len(acts))])


for act in activities:
    activities_num.append(activities_counts[act])
print activities



pylab.bar(left=range(len(activities)),height=activities_num) 
pylab.xticks(range(len(activities)),activities, rotation=70)
pylab.xlabel("activity")
pylab.ylabel("numbers")
pylab.autoscale=True
pylab.savefig("./pictures/num of activities")
pylab.show()

['Bathe', 'Bed_Toilet_Transition', 'Cook', 'Cook_Breakfast', 'Cook_Dinner', 'Cook_Lunch', 'Dress', 'Eat', 'Eat_Breakfast', 'Eat_Dinner', 'Eat_Lunch', 'Enter_Home', 'Entertain_Guests', 'Evening_Meds', 'Groom', 'Leave_Home', 'Morning_Meds', 'Personal_Hygiene', 'Phone', 'Read', 'Relax', 'Sleep', 'Sleep_Out_Of_Bed', 'Take_Medicine', 'Toilet', 'Wash_Breakfast_Dishes', 'Wash_Dinner_Dishes', 'Wash_Dishes', 'Wash_Lunch_Dishes', 'Watch_TV', 'Work', 'Work_At_Table', 'Work_On_Computer']


次数：
[44, 49, 33, 48, 79, 62, 119, 36, 52, 42, 49, 147, 16, 14, 62, 234, 32, 462, 55, 82, 19, 106, 7, 60, 173, 43, 30, 30, 39, 129, 7, 37, 258]

标签：
['Bathe', 'Bed_Toilet_Transition', 'Cook', 'Cook_Breakfast', 'Cook_Dinner', 'Cook_Lunch', 'Dress', 'Eat', 'Eat_Breakfast', 'Eat_Dinner', 'Eat_Lunch', 'Enter_Home', 'Entertain_Guests', 'Evening_Meds', 'Groom', 'Leave_Home', 'Morning_Meds', 'Personal_Hygiene', 'Phone', 'Read', 'Relax', 'Sleep', 'Sleep_Out_Of_Bed', 'Take_Medicine', 'Toilet', 'Wash_Breakfast_Dishes', 'Wash_Dinner_Dishes', 'Wash_Dishes', 'Wash_Lunch_Dishes', 'Watch_TV', 'Work', 'Work_At_Table', 'Work_On_Computer']

柱状图：
![](./pictures/num of activities.png)


2.  每种行为触发的传感器数量

    首先创建一个dataframe，index为行为，col为传感器
    得到每个观测序列的前38个特征

In [11]:
import numpy as np
from utils import ExtractActivities
from StringIO import StringIO

filename = "./data/ann.txt"
activities = ExtractActivities(filename)
file_bin_sensors = "./data/bin_sensors.txt"
bin_sensors = np.loadtxt(file_bin_sensors,dtype=np.str)
con_sensors = np.loadtxt("./data/continue_sensors.txt",dtype=np.str)
labels = np.loadtxt("./data/activities.txt",dtype=np.str)

def onlybin(activity):
    bin_activity = [activity[0]]
    for i in range(1,len(activity)):
        if len(activity[i]) == 4 and activity[i][2] in bin_sensors:
            bin_activity.append(activity[i])
    return bin_activity


activities = ExtractActivities(filename)
# print onlybin(activities[0])
bin_activities = []
# for activity in activities[0:20]:
for activity in activities:
    bin_activities.append(onlybin(activity))
print bin_activities[0]
bin_activities = np.array(bin_activities)
activity_labels = [activity[0] for activity in bin_activities]
activity_labels = np.array(activity_labels)
print bin_activities.shape
print("end")

['Sleep', ['2011-06-15', '02:13:20.812509', 'M007', 'ON'], ['2011-06-15', '02:13:21.919635', 'M007', 'OFF'], ['2011-06-15', '05:40:14.111389', 'M021', 'ON']]
(2655L,)
end


In [46]:
import pandas as pd
# print bin_sensors
df_activity_sensor = pd.DataFrame(index=np.arange(bin_activities.shape[0]),columns=bin_sensors)
activity_sensor_times = np.array([[0 for x in range(len(bin_sensors))] 
                                  for i in range(len(bin_activities))],dtype=np.float16)

for i in range(0,len(bin_activities)):
    current_act = bin_activities[i]
    for j in range(1,len(current_act)):
        col_index = list(bin_sensors).index(current_act[j][2])
        activity_sensor_times[i,col_index] += 1
# total_times = activity_sensor_times.sum(axis=1)
# tf = activity_sensor_times / total_times[:,np.newaxis]
index = (activity_labels=="Eat")
# print index
# print(activity_sensor_times[index][0])
# np.savetxt('./data/sleep_sensor_times.txt',activity_sensor_times[index])
# print(bin_sensors)
current_activity_sensor = activity_sensor_times[index]
                                  
index_actsensor = (current_activity_sensor.sum(axis=0) > 0)
# print bin_sensors
# print index_actsensor
print bin_sensors[index_actsensor]
print current_activity_sensor[:,index_actsensor]

['M001' 'M003' 'M009' 'M010' 'M014' 'M016' 'M020' 'MA022' 'MA023' 'MA024']
[[   0.    0.    0.    0.    0.   76.    0.   12.    1.    0.]
 [   0.    0.    0.    0.    0.  126.    0.   10.    0.    0.]
 [   0.    0.    0.    0.    0.   36.    0.    9.    0.    0.]
 [   0.    2.    0.    0.    0.   66.    0.   10.    4.    0.]
 [   0.    0.    0.    0.    0.   28.    0.    1.    0.    0.]
 [   0.    0.    0.    0.    6.   18.    0.    9.    6.    0.]
 [   0.    0.    0.    0.    0.   42.    0.    4.    0.    0.]
 [   0.    0.    0.    0.    0.   86.    0.   11.    0.    0.]
 [   0.    0.    0.    0.    0.   45.    0.   23.    0.    0.]
 [   0.    0.    0.    0.    6.   66.    0.   13.    4.    0.]
 [   0.    0.    0.    0.    4.   40.    0.   14.    4.    0.]
 [   0.    0.    0.    0.    0.   70.    0.    8.    0.    0.]
 [   0.    0.    0.    0.    0.   34.    0.    6.    0.    0.]
 [   0.    0.    0.    0.    0.  162.    4.   18.    0.    0.]
 [   2.    0.   62.    0.    0.    0.    0.

In [48]:
index = (activity_labels=="Phone")
# print index
# print(activity_sensor_times[index][0])
# np.savetxt('./data/sleep_sensor_times.txt',activity_sensor_times[index])
# print(bin_sensors)
current_activity_sensor = activity_sensor_times[index]
                                  
index_actsensor = (current_activity_sensor.sum(axis=0) > 0)
# print bin_sensors
# print index_actsensor
print bin_sensors[index_actsensor]
print current_activity_sensor[:,index_actsensor]

['M002' 'M008' 'M010' 'M014' 'M015' 'M016' 'M020' 'MA022' 'MA023']
[[   0.    2.    0.   24.    0.    0.    0.    3.    4.]
 [   0.    1.    0.    8.    0.    0.    0.    2.    2.]
 [   0.    1.    0.   12.    0.    0.    0.    3.    6.]
 [   0.    2.    0.   20.    0.    0.    0.    4.    3.]
 [   0.    6.    0.   24.    0.    0.    0.    4.    6.]
 [   0.    0.    0.   12.    0.    0.    0.    2.    4.]
 [   0.    0.    0.   20.    0.    0.    0.    1.    2.]
 [   0.    1.    0.   12.    0.    0.    0.    1.    0.]
 [   0.    1.    0.   18.    0.    0.    0.    2.    0.]
 [   0.    1.    0.   22.    0.    0.    0.    2.    2.]
 [   0.    2.    0.   26.    0.    0.    0.    2.    3.]
 [   0.    2.    0.   32.    0.    0.    0.    7.    7.]
 [   0.    1.    0.   22.    0.    0.    0.    0.    6.]
 [   0.    5.    0.   22.    0.    0.    0.    0.    2.]
 [   0.    0.    0.    0.    0.   20.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    8.    0.    3.    0.]
 [   0.    0.    0.  